'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),test=require('node:test'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'src/static/app.js'),'utf8');
function fn(name){const starts=[source.indexOf(`function ${name}(`),source.indexOf(`async function ${name}(`)].filter(n=>n>=0);assert.ok(starts.length,name);const start=Math.min(...starts);let depth=0;for(let i=source.indexOf('{',source.indexOf(')',start));i<source.length;i++){if(source[i]==='{')depth++;if(source[i]==='}')depth--;if(!depth)return source.slice(start,i+1);}throw Error(name);}
function setup(){let resolve;const pending=new Promise(ok=>resolve=ok);let view='project',renders=0;const document={activeElement:null,getElementById:()=>({classList:{contains:()=>view==='project',add(){},remove(){},toggle(){}}}),querySelectorAll:()=>[],querySelector:()=>null};const s={console,document,currentProject:{id:7,name:'cached'},allProjects:[{id:7}],projectDetailCache:new Map([[7,{id:7,name:'cached'}]]),projectSelectionVersion:0,projectNavigationVersion:0,projectEditVersion:0,promoteProjectPrefetch(){},storeProjectDetail:p=>p,requestProjectDetail:()=>pending,renderProjectDetail(p){s.currentProject=p;view='project';renders++;},showViewLoading(){},toast(){},invalidateProjectTabRenders(){},activeProjectTabName(){return 'info';},ensureProjectTabRendered(){},safeRender(){renders++;},renderSidebar(){},renderProjectTopbar(){},renderBoard(){},renderTimeline(){},renderTasks(){},renderInfo(){},renderAttachments(){},invalidateProjectViews(){},loadDashboard(){},loadCalendar(){},loadProcureBoard(){},loadSettingsView(){},playViewEnter(){},isEditingApplicationForm:()=>Boolean(document.activeElement)};vm.createContext(s);vm.runInContext(fn('selectProject')+'\n'+fn('refreshProject')+'\n'+fn('switchView'),s);return {s,resolve,setView:v=>{view=v;},get view(){return view;},get renders(){return renders;}};}
test('late project response does not return from settings to the project',async()=>{const h=setup();const pending=h.s.selectProject(7);h.s.switchView('settings');h.setView('settings');h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.view,'settings');assert.equal(h.renders,1);});
test('cached project response does not redraw after the user starts typing',async()=>{const h=setup();const pending=h.s.selectProject(7);h.s.projectEditVersion++;h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.renders,1);});
test('refresh of an old project never replaces a newly selected project',async()=>{const h=setup();const pending=h.s.refreshProject();h.s.currentProject={id:8,name:'new selection'};h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.s.currentProject.id,8);assert.equal(h.renders,0);});
test('refresh avoids rebuilding a form being edited',async()=>{const h=setup();const pending=h.s.refreshProject();h.s.document.activeElement={};h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.renders,0);});
test('IME Escape does not close the editing dialog',()=>{const bootstrap=fs.readFileSync(path.join(root,'source/frontend/08-bootstrap.js'),'utf8');const code=bootstrap.slice(bootstrap.indexOf("document.addEventListener('keydown', e =>"),bootstrap.indexOf("window.addEventListener('pagehide'"));let handler,closed=0;vm.runInNewContext(code,{document:{addEventListener:(_,cb)=>handler=cb,getElementById:()=>null},closeCommandPalette(){},closeModal(){closed++;},closeSlide(){closed++;}});handler({key:'Escape',isComposing:true});assert.equal(closed,0);handler({key:'Escape',keyCode:229});assert.equal(closed,0);});
test('canceling uncached navigation preserves the previous form without loading placeholders',async()=>{const h=setup();h.s.projectDetailCache.clear();h.s.currentProject={id:6,name:'old project'};let loading=0;h.s.showViewLoading=()=>loading++;const pending=h.s.selectProject(7);h.s.projectEditVersion++;h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.s.currentProject.id,6);assert.equal(loading,0);assert.equal(h.renders,0);});
test('changing tabs during uncached loading keeps the previous project usable',async()=>{const h=setup();h.s.projectDetailCache.clear();h.s.currentProject={id:6,name:'old project'};let loading=0;h.s.showViewLoading=()=>loading++;const pending=h.s.selectProject(7);h.s.projectNavigationVersion++;h.resolve({accepted:true,project:{id:7,name:'fresh'}});await pending;assert.equal(h.s.currentProject.id,6);assert.equal(loading,0);});
