const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const file=path.join(__dirname,'../source/frontend/00-icons.js');
function load(html){const dom=new JSDOM(html,{runScripts:'outside-only'});dom.window.eval(fs.readFileSync(file,'utf8'));dom.window.PMIcons.render(dom.window.document.body);return dom;}
test('custom icons cover interface glyphs and remain fixed size colored SVG',()=>{const dom=load('<button><span data-ui-icon="⚡"></span> 批量操作</button><h3><span data-ui-icon="✅"></span> 文件定稿</h3><span><span data-ui-icon="📋"></span> 委托协议</span>');const d=dom.window.document;assert.equal(d.querySelectorAll('svg.pm-icon').length,3);assert.equal(d.querySelector('svg').getAttribute('viewBox'),'0 0 24 24');assert.match(d.querySelector('svg').outerHTML,/--icon-/);assert.equal(d.querySelector('button').textContent.trim(),'批量操作');dom.window.close();});
test('icon rendering preserves business text, logo, form values and selected options',()=>{const dom=load('<div class="logo">📦 Logo</div><span data-ui-content>✅ 项目名称</span><div class="project-name">📢 项目</div><p>✅ 没有标记的业务备注 📥</p><input value="✅ 备注"><textarea>⚡ 备注</textarea><select><option value="✅">完成</option></select>');const d=dom.window.document;assert.equal(d.querySelectorAll('svg').length,0);assert.equal(d.querySelector('input').value,'✅ 备注');assert.equal(d.querySelector('textarea').value,'⚡ 备注');assert.equal(d.querySelector('select').value,'✅');dom.window.close();});
test('newly rendered controls receive icons without repeated decoration or lost click handlers',async()=>{const dom=load('<main></main>');const d=dom.window.document;let clicks=0;const b=d.createElement('button');b.innerHTML='<span data-ui-icon="📥"></span> 接收';b.addEventListener('click',()=>clicks++);d.querySelector('main').append(b);await new Promise(r=>setTimeout(r,30));assert.equal(b.querySelectorAll('svg').length,1);dom.window.PMIcons.render(b);assert.equal(b.querySelectorAll('svg').length,1);b.click();assert.equal(clicks,1);dom.window.close();});
test('icon-only stage selectors retain stored emoji while offering custom icon preview',()=>{const dom=load('<label>图标<select data-stage-template-field="icon"><option value="📥">📥</option><option value="✅">✅</option></select></label>');const d=dom.window.document;assert.equal(d.querySelector('select').value,'📥');assert.equal(d.querySelectorAll('.pm-icon-select-preview svg').length,1);const select=d.querySelector('select');select.value='✅';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));assert.equal(select.value,'✅');assert.equal(d.querySelector('.pm-icon-select-preview svg').dataset.icon,'check');dom.window.close();});

test('emoji-only business choices retain their visible names',()=>{const dom=load('<select><option value="✅">✅</option><option value="📝">📝</option></select>');assert.equal(dom.window.document.querySelectorAll('svg,.pm-icon-select-wrap').length,0);assert.equal(dom.window.document.querySelector('select').value,'✅');dom.window.close();});
test('unknown custom stage icons remain visible in the icon picker',()=>{const dom=load('<select data-stage-template-field="icon"><option value="🚜">🚜</option><option value="✅">✅</option></select>');assert.equal(dom.window.document.querySelector('.pm-icon-select-preview').textContent,'🚜');assert.equal(dom.window.document.querySelector('select').value,'🚜');dom.window.close();});
