const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PM_PLAYWRIGHT_MODULE || 'playwright');
const assets=path.resolve(process.env.PM_UI_ASSETS || '_build/purchaser-workspace/assets'),out=path.resolve(process.env.PM_UI_OUTPUT || '_build/unified-improvements/ui');fs.mkdirSync(out,{recursive:true});
let html=fs.readFileSync(path.join(assets,'templates/workspace.html'),'utf8').replace(/{{ current_user_id \| tojson }}/g,'1').replace(/{{ current_username \| tojson }}/g,'"review"').replace(/{{ current_is_admin \| tojson }}/g,'true').replace(/{{ csrf_token \| tojson }}/g,'"review"');
const keys=['plan_received','doc_prepare','doc_review','doc_finalized','agreement_signed','announcement','registration_end','bid_opening','evaluation','result_announced','winning_notice','service_fee','deposit_refund','archived'];
const names=['计划接收','文件编制','文件审核','文件定稿','委托协议签定','公告发布','报名截止','开标','评标','结果公示','中标通知书','服务费到账','保证金退还','资料整理归档'];
const methods=['公开招标','竞争性磋商','竞争性谈判','邀请招标','网上竞价','单一来源','遴选','直选'];
const projects=Array.from({length:16},(_,i)=>({id:i+1,number:`PRJ-2026-${String(i+1).padStart(3,'0')}`,name:['市民服务中心办公设备与配套设施采购项目','社区公共卫生服务能力提升项目','学校智慧教学平台及网络改造服务项目'][i%3],year:2026,purchaser:'实验学校',method:methods[i%8],budget:'100万元',progress:Math.round((i%5)/14*100),current_stage_key:keys[i%5],current_stage_name:names[i%5],stages:keys.map((k,n)=>({key:k,name:names[n],completed:n<i%5,skipped:false,planned_at:`2026-09-${String(10+n).padStart(2,'0')}T09:30:00`,checklist:[]})),lots:[],suppliers:[],attachments:[],activity:[]}));
(async()=>{
const b=await chromium.launch({headless:true,executablePath:process.env.PM_EDGE_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
const p=await b.newPage({viewport:{width:1366,height:768}});const errors=[],requests=[];p.on('pageerror',e=>errors.push(String(e)));
await p.route('**/*',async r=>{const u=new URL(r.request().url()),q=u.pathname;requests.push(q);if(q.startsWith('/static/')){let f=['/static/style.css','/static/app.js'].includes(q)?path.resolve('src'+q):path.join(assets,q);return fs.existsSync(f)?r.fulfill({path:f}):r.fulfill({status:404,body:''});}if(!q.startsWith('/api/'))return r.fulfill({contentType:'text/html',body:html});let data={};if(q==='/api/projects')data=projects;else if(/^\/api\/projects\/\d+$/.test(q))data=projects[+q.split('/').pop()-1];else if(q==='/api/stats')data={total:16,in_progress:16,completed:0,liubiao:0,feibiao:0};else if(q==='/api/system-info')data={version:'v5.8.12',license:{},is_admin:true,is_desktop:true,export_dir:'C:/ProcurementProjectManager/exports',data_dir:'C:/ProcurementProjectManager',backup_dir:'C:/ProcurementProjectManager/backups'};else if(q==='/api/settings')data={categories:[],units:[],groups:[{name:'教育单位',color:'#2563eb',units:[{name:'实验学校',project_count:16,project_ids:projects.map(p=>p.id),recent_project:projects[0].name}]}],is_admin:true,reminder_recipient_groups:[],supplier_minimums:{}};else if(q==='/api/calendar')data={weekday_names:['一','二','三','四','五','六','日'],cells:Array.from({length:35},(_,i)=>i===0||i>new Date(+u.searchParams.get('year'),+u.searchParams.get('month'),0).getDate()?{empty:true}:{day:i,date_str:u.searchParams.get('year')+'-'+u.searchParams.get('month').padStart(2,'0')+'-'+String(i).padStart(2,'0'),events:i%3?[]:[{project_id:1,project_name:projects[0].name,stage_name:'开标评标',planned_time:'09:30',icon:'📌'}]})};return r.fulfill({json:data});});
projects[0].lots=[{id:1,lot_number:'包1',lot_name:'信息设备采购',budget:120000},{id:2,lot_number:'包2',lot_name:'运行维护服务',budget:80000}];projects[0].registrations=[{id:1,lot_id:1,company_name:'示例供应商',bidder_type:'standalone',registration_method:'线上报名',manager_phone:'13800000000'}];
await p.goto('http://127.0.0.1:59998/',{waitUntil:'networkidle'});await p.waitForTimeout(600);


const checks=[],metrics=[];
await p.route('**/api/attachments/1/view',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="640" height="400"><rect width="640" height="400" fill="#e0e7ff"/></svg>'}));
await p.evaluate(()=>selectProject(1));
const scenarios=[
{name:'batch-dates',open:()=>p.evaluate(()=>batchSetPlannedDate()),host:'#modal',controls:'#batchStartDate,#batchInterval,.bd-at'},
{name:'project-import',open:()=>p.evaluate(()=>showProjectImportDialog()),host:'#modal',controls:'#projectImportFile,.modal-footer button'},
{name:'registration-import',open:()=>p.evaluate(()=>showRegistrationImportDialog()),host:'#modal',controls:'#registrationImportFile'},
{name:'upload',open:()=>p.evaluate(()=>{switchView('project');switchProjectTab('attachments');}),host:'#uploadArea',controls:'#uploadArea'},
{name:'confirm',open:()=>p.evaluate(()=>{confirmDialog('确认操作','请确认项目与阶段信息。');}),host:'#confirmDialog',controls:'#confirmDialog button'},
{name:'reason',open:()=>p.evaluate(()=>{reasonDialog('操作原因','原因','填写原因');}),host:'#reasonDialog',controls:'#reasonInput'},
{name:'batch-advance',open:()=>p.evaluate(()=>openBatchAdvanceDialog()),host:'#batchAdvanceDialog',controls:'#batchAdvanceDialog select,#baModeStage'},
{name:'stage-expanded',open:async()=>{await p.evaluate(()=>{openStageSlide('plan_received');});await p.locator('.stage-optional-notes summary').click();},host:'#slidePanel',controls:'.stage-optional-notes summary,#stageNotes'},
{name:'settings-files',open:()=>p.evaluate(async()=>{settingsFormDirty=false;switchView('settings');await loadSettingsView();setSettingsCategory('files');document.querySelector('.settings-details').open=true;}),host:'#settingsContent',controls:'.settings-details summary'},
{name:'project-management',open:()=>p.evaluate(()=>{switchView('project');switchProjectTab('info');}),host:'.info-form',controls:'#infoNumber,#infoPurchaser'},
{name:'attachments-batch',open:()=>p.evaluate(()=>{switchView('project');currentProject.attachments=[{id:1,filename:'项目资料.pdf',extension:'pdf',file_size:1024,is_pdf:true},{id:2,filename:'采购方案.docx',extension:'docx',file_size:2048}];switchProjectTab('attachments');renderAttachments();batchDeleteAttachments();}),host:'#attachmentBatchBar',controls:'#attachmentBatchBar button'},
{name:'preview',open:()=>p.evaluate(()=>{openDocPreview({id:1,filename:'项目资料.svg',extension:'svg'},'image',1);}),host:'#docPreviewOverlay',controls:'.doc-pt-btn,.doc-pt-select'}
];
for(const category of ['general','workflow','email','system','device-access','about'])scenarios.push({name:'settings-'+category,open:()=>p.evaluate(async category=>{settingsFormDirty=false;switchView('settings');await loadSettingsView();setSettingsCategory(category);},category),host:'#settingsContent',controls:'#settingsContent button,#settingsContent input,#settingsContent select'});
for(const view of ['dashboard','procure','purchasers'])scenarios.push({name:view,open:()=>p.evaluate(view=>switchView(view),view),host:'#view-'+view,controls:'#view-'+view+' button'});
scenarios.push({name:'registration-form',open:()=>p.evaluate(()=>showRegistrationForm()),host:'#modal',controls:'#modal input,#modal select'});
scenarios.push({name:'bid-result-form',open:()=>p.evaluate(()=>showBidResultForm()),host:'#modal',controls:'#modal input,#modal select'});
async function cleanup(){await p.evaluate(()=>{document.getElementById('confirmCancel')?.click();document.getElementById('reasonCancel')?.click();closeDocPreview();closeBatchAdvanceDialog();closeSlide();closeModal();closeRecipientGroupDrawer();closeSidebar();document.querySelectorAll('.toast').forEach(el=>el.classList.remove('show'));});}
for(const theme of ['default','blue','green','dark'])for(const width of [390,1024,1366])for(const spec of scenarios){
try{
 await cleanup();await p.setViewportSize({width,height:844});await p.evaluate(theme=>applyTheme(theme),theme);await spec.open();await p.waitForTimeout(350);
 const metric=await p.locator(spec.host).evaluate((el,controls)=>{const r=el.getBoundingClientRect();const s=getComputedStyle(el);return {bounds:{x:r.x,y:r.y,width:r.width,height:r.height},overflow:el.scrollWidth>el.clientWidth+1,bg:s.backgroundColor,color:s.color,controls:[...document.querySelectorAll(controls)].map(x=>{const v=getComputedStyle(x),q=x.getBoundingClientRect();return {visible:q.width>0&&q.height>0,id:x.id,type:x.type,text:x.textContent.slice(0,25),background:v.backgroundColor,color:v.color,radius:v.borderRadius,height:q.height,width:q.width,left:q.left,right:q.right}})};},spec.controls);
 metrics.push({theme,width,name:spec.name,...metric});
 if(width===390 || (theme==='dark' && width===1366))await p.screenshot({path:path.join(out,`${spec.name}-${theme}-${width}.png`)});
 const visible=metric.controls.filter(x=>x.visible);const issues=[];if(metric.overflow)issues.push('host overflow');if(metric.bounds.width<=0||metric.bounds.height<=0)issues.push('host hidden');if(metric.bounds.x<-1||metric.bounds.x+metric.bounds.width>width+1)issues.push('host outside viewport');if(visible.some(x=>x.left<-1||x.right>width+1))issues.push('control outside viewport');if(spec.name==='confirm'){const expected=await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--text').trim());const cancel=await p.locator('#confirmCancel').evaluate(el=>{const probe=document.createElement('span');probe.style.color='var(--text)';document.body.appendChild(probe);const expected=getComputedStyle(probe).color;probe.remove();return {color:getComputedStyle(el).color,expected};});if(cancel.color!==cancel.expected)issues.push('cancel text theme mismatch');}if(spec.name==='batch-dates'&&visible.some(x=>x.radius!=='8px'||x.height<39))issues.push('batch date control mismatch');if(spec.name==='reason'&&visible[0]?.background!==metric.bg)issues.push('reason surface mismatch');if(theme==='dark'&&spec.name==='attachments-batch'&&metric.bg==='rgb(254, 242, 242)')issues.push('light error surface');checks.push({theme,width,name:spec.name,passed:!issues.length,issues});
}catch(e){checks.push({theme,width,name:spec.name,passed:false,error:String(e)});}
}
for(const theme of ['default','blue','green','dark']){try{await cleanup();await p.evaluate(theme=>{applyTheme(theme);showNewProjectModal();},theme);const button=p.locator('#modal button.btn-primary:visible').first();await p.mouse.move(0,0);const token=await button.evaluate(el=>{const probe=document.createElement('span');probe.style.background='var(--primary)';document.body.appendChild(probe);const expected=getComputedStyle(probe).backgroundColor;probe.remove();return {expected,bg:getComputedStyle(el).backgroundColor};});assert.equal(token.bg,token.expected,theme+' normal button');await button.focus();await p.waitForTimeout(200);const focused=await button.evaluate(el=>{const probe=document.createElement('span');probe.style.background='var(--primary-hover)';document.body.appendChild(probe);const expected=getComputedStyle(probe).backgroundColor;probe.remove();return {expected,bg:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color};});assert.equal(focused.bg,focused.expected,theme+' focused button');assert.equal(focused.color,'rgb(255, 255, 255)');await button.hover();await p.waitForTimeout(200);assert.equal(await button.evaluate(el=>getComputedStyle(el).backgroundColor),focused.expected,theme+' hovered button');await button.evaluate(el=>el.blur());await button.hover();await p.mouse.down();await p.waitForTimeout(200);assert.equal(await button.evaluate(el=>getComputedStyle(el).backgroundColor),focused.expected,theme+' mouse focused button');await p.mouse.up();await p.evaluate(()=>{closeModal();confirmDialog('确认操作','主题检查');});const secondary=p.locator('#confirmCancel');const textColor=await secondary.evaluate(el=>{const probe=document.createElement('span');probe.style.color='var(--text)';document.body.appendChild(probe);const value=getComputedStyle(probe).color;probe.remove();return value;});for(const action of ['hover','focus','mouse-focus']){if(action==='hover')await secondary.hover();else if(action==='focus'){await secondary.focus();}else{await secondary.evaluate(el=>el.blur());await secondary.hover();await p.mouse.down();}await p.waitForTimeout(200);assert.equal(await secondary.evaluate(el=>getComputedStyle(el).color),textColor,theme+' secondary '+action);if(action==='mouse-focus')await p.mouse.up();}checks.push({name:'spreadsheet CSS preserves application button theme',theme,passed:true,normalBackground:token.bg,focusedBackground:focused.bg,focusedText:focused.color,secondaryText:textColor});}catch(e){checks.push({name:'spreadsheet CSS preserves application button theme',theme,passed:false,error:String(e)});}}
fs.writeFileSync(path.join(out,'consistency.json'),JSON.stringify({checks,metrics,errors},null,2));console.log(JSON.stringify({total:checks.length,failed:checks.filter(c=>!c.passed),errors}));if(checks.some(c=>!c.passed)||errors.length)process.exitCode=1;
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
